config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :homes, only: [:index, :show]

  resources :properties do
    collection do
      get :export_xlsx
      get :export_pdf
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  # relations
  belongs_to :user

  # validations
  validates :price, numericality: { greater_than: 0 }
  validates :operation, :property_type, :currency_type, :commune, presence: true
  validate :validate_images
  
  # enum
  enum operation: [:VENTA, :ARRIENDO]
  enum property_type: [:CASA, :DEPTO, :OFICINA, :TERRENO]
  enum currency_type: [:CLP, :UF]

  # activestorage
  has_many_attached :images

  private 

  def validate_images
    unless images.attached? && images.length >= 3
      errors.add(:images, "Debe ingresar un min de 3 imagenes")
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :properties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @properties = Property.all
  end
  
  def show 
    @property = Property.find(params[:id])
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:update, :destroy]

  def index
    if current_user.present?
      @properties = current_user.properties 
    else
      redirect_to homes_path
    end
  end

  def show
    @property = current_user.properties.where(id: params[:id]).last if current_user.present?
    if @property.nil?
      flash[:alert] = "No estas autorizado para ver la propiedad"
      redirect_to properties_path
    end
  end

  def new
    @property = Property.new
  end

  def edit
    @property = current_user.properties.where(id: params[:id]).last if current_user.present?
    if @property.nil?
      flash[:alert] = "No estas autorizado para ver la propiedad"
      redirect_to properties_path
    end
  end

  def create
    @property = current_user.properties.new(property_params)

    if @property.save
      redirect_to @property, notice: 'Propiedad Creada correctamente!'
    else
      redirect_to new_property_path,  alert: 'No se pudo crear la propiedad' 
    end
  end

  def update
    if @property.update(property_params)
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      redirect_to edit_property_path(@property),  alert: 'No se pudo actualizar la propiedad' 
    end
  end

  def destroy
    @property.destroy
    redirect_to properties_url, notice: 'Se ha eliminado correctamente'
  end

  def export_xlsx
    @properties = current_user.properties
    respond_to do |format|
      format.xlsx { render xlsx: 'export_xlsx', filename: "reporte_propiedades.xlsx"}
    end
  end

  def export_pdf
  end

  private

  def set_property 
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:operation, :property_type, :price, :currency_type, :commune, :address, :area, :bedrooms, :bathrooms, :user_id, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/homes/index.html.erb
<div class="container" data-controller="home">
  <h1 class="p-2">Propiedades que pueden interesarte</h1>

  <div class="container">
    <div class="row">
      <% @properties.each do |property| %>
        <div class="col-4">
          <div class="card" style="width: 18rem;">
            <%= image_tag property.images.first.variant(resize: "300x300") %>
            <div class="card-body">
              <h5 class="card-title"><%= property.commune %> - <%= property.currency_type %> <%= property.price.round %></h5>
              <p><%= property.operation %> </p>
              <p class="card-text"></p>
              <%= link_to 'Ver más', home_path(property), class:"btn btn-primary"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/show.html.erb
<div class="container ">
  <div class="row">
    <div class="col-3">
      <%= image_tag @property.images.first.variant(resize: "300x300") %>
    </div>
    <div class="col-4">
      <ul class="list-group">
        <li class="list-group-item"><strong>ID:</strong> <%= @property.id %></li>
        <li class="list-group-item"><strong>Operación:</strong> <%= @property.operation %></li>
        <li class="list-group-item"><strong>Tipo de propiedad:</strong> <%= @property.property_type %></li>
        <li class="list-group-item"><strong>Precio:</strong> <%= number_to_currency(@property.price, unit: @property.currency_type) %></li>
        <li class="list-group-item"><strong>Comuna:</strong> <%= @property.commune %></li>
        <li class="list-group-item"><strong>Dirección:</strong> <%= @property.address %></li>
        <li class="list-group-item"><strong>Área:</strong> <%= @property.area %> m²</li>
        <li class="list-group-item"><strong>Dormitorios:</strong> <%= @property.bedrooms %></li>
        <li class="list-group-item"><strong>Baños:</strong> <%= @property.bathrooms %></li>
      </ul>
    </div>
    <div class="col-12">
      <%= link_to 'Volver', homes_path, class:'btn btn-primary'  %>
    </div>
  </div>
  
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-light bg-light justify-content-between p-3">
  <%= link_to 'My Properties', root_path, class: 'navbar-brand'%>
  <div class=" d-flex ">
    <% if current_user.present? %>
      <%= link_to "Mis Proyectos", properties_path(), class:'nav-link m-2' %>
      <a class="nav-link m-2"><%= current_user.email%></a>
    <% else %>
      <%= link_to 'Inicia Sesión', user_session_path, class:'nav-link m-1' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProperties</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
  <%= form_with(model: @property, local: true) do |form| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@property.errors.count, "error") %> Hubo un error al guardar la propiedad</h2>
  
        <ul>
        <% @property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  <div class="row">
    <div class="col-9">
      <div class="row justify-content-center">
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Operación' %>
            <%= form.select :operation, Property.operations.keys, {}, class: 'form-select' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Tipo' %>
            <%= form.select :property_type, Property.property_types.keys, {}, class: 'form-select' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Tipo de divisa' %>
            <%= form.select :currency_type, Property.currency_types.keys, {}, class: 'form-select' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Precio' %>
            <%= form.text_field :price, class: 'form-control' %>
          </div>
        </div>
    
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Comuna' %>
            <%= form.text_field :commune, class: 'form-control' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Dirección' %>
            <%= form.text_field :address, class: 'form-control' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Area' %>
            <%= form.text_field :area, class: 'form-control' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Habitaciones' %>
            <%= form.number_field :bedrooms, class: 'form-control' %>
          </div>
        </div>
        <div class="col-3 m-1">
          <div class="form-group">
            <%= form.label 'Baños' %>
            <%= form.number_field :bathrooms, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="row">
        <div class="col-12">
          <div class="form-group">
            <%= form.label :images, "Upload Images" %>
            <%= form.file_field :images, multiple: true, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 d-flex">
      <div class="actions">
        <%= form.submit class: 'btn btn-primary m-1' %>
      </div>
      
      <%= link_to 'Volver', properties_path, class: 'btn btn-secondary m-1' %>
    </div>
  </div>


<% end %>

app/views/properties/edit.html.erb
<div class="container">
  <h1 class="text-center">Editar Propiedad <%= @property.id%></h1>
    
  <%= render 'form', property: @property %>
</div>    

app/views/properties/index.html.erb
<div class="container">
  <h1> Mis propiedades</h1>
  <%= link_to 'Crear Propiedad', new_property_path(), class: 'btn btn-primary m-1'%>
  <%= link_to "Descargar Excel", export_xlsx_properties_path(format: "xlsx"), class: 'btn btn-primary' %>
  <table class="table table-bordered" data-controller="property">
    <thead>
      <tr>
        <th scope="col">#ID</th>
        <th scope="col">Operación</th>
        <th scope="col">Tipo</th>
        <th scope="col">Tipo de divisa</th>
        <th scope="col">Precio</th>
        <th scope="col">Fecha de Creación</th>
        <th scope="col">actions</th>
      </tr>
    </thead>
    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <th scope="row"><%= property.id %></th>
          <td><%= property.operation %></td>
          <td><%= property.property_type %></td>
          <td><%= property.currency_type %></td>
          <td><%= property.price.round %></td>
          <td><%= property.created_at.strftime('%d/%m/%Y') %></td>
          <td class="">
            <%= link_to 'Ver', property_path(property), class:'btn btn-primary' %>
            <%= link_to 'Editar', edit_property_path(property), class:'btn btn-warning'%>
            <%= link_to 'Eliminar', property_path(property), class:'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/properties/new.html.erb
<div class="container">
  <h1 class="text-center">Nueva Propiedad</h1>
    
  <%= render 'form', property: @property %>

</div>

app/views/properties/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="m-3">Mi Propiedad n° <%= @property.id%></h1>
    </div>
    <div class="col-3 bg-info p-3">
      <!-- imagen aqui -->
      <% @property.images.each do |image| %>
        <%= image_tag image.variant(resize: "300x300") %>
      <% end %>
    </div>
    <div class="col-9 p-3">
      <ul class="list-group">
        <li class="list-group-item">
          <%= label_tag 'id', 'Id:' %>
          <%= @property.id %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'operation', 'Operación:' %>
          <%= @property.operation %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'property_type', 'Tipo:' %>
          <%= @property.property_type %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'price', 'Precio:' %>
          <%= @property.price.round %> <%= @property.currency_type %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'commune', 'Comuna:' %>
          <%= @property.commune %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'address', 'Dirección:' %>
          <%= @property.address %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'area', 'Area:' %>
          <%= @property.area %> mts
        </li>
        <li class="list-group-item">
          <%= label_tag 'bedrooms', 'Habitaciones:' %>
          <%= @property.bedrooms %>
        </li>
        <li class="list-group-item">
          <%= label_tag 'bathrooms', 'Baños:' %>
          <%= @property.bathrooms %>
        </li>
    </div> 
    <div class="col-12">
      <%= link_to 'Volver', properties_path, class:'btn btn-primary m-1' %>
      <%= link_to 'Editar', edit_property_path(@property), class:'btn btn-primary m-1' %>
    </div>
  </div>
</div>